### ISSUE TITLE
Remove the requirement of updating the PATH on Mac OS

### ISSUE THREAD

**Issue by guhcampos** [pearl-core/pearl#58]
Currently, Pearl requires the GNU coreutils to work on the Mac. Pearl docs instruct installing this dependency with Homebrew, which introduces a requirement for hard coding `PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"` into the user shell configuration.

This might be undesirable as it breaks several expected behaviors for conflicting binaries. As an example, `readlink` usage is quite different and even`ls` has a different syntax on both platforms, so favoring their GNU counterparts will lead to unexpected results and lots of broken shell scripts.

So for example in line 21 of the main pearl script, the following code:
`$(readlink -f $(dirname $(readlink -f "$0"))/..)}"`

could be prepended by setting the PATH variable locally to either the hard coded `/opt/coreutils/libexec/gnubin` (as it's already a hard requirement anyway) or a user configuration in pearl.conf. That way the user's PATH remains untouched and uses of homonym commands will call the native counterparts.

**Comment by fsquillace** [comment]
Hi Gustavo,

I agree with you on this. Forcing the use to have the GNU coreutils might not be a good idea.

The only reason I forced it is because there are few packages that still requires GNU coreutils anyway. For instance [kyrat](https://github.com/pearl-hub/kyrat/blob/master/bin/kyrat#L50) is an example.

What I can do is following your approach. I can define a bash module like `osx-compat.sh` which will be sourced from all scripts that have GNU coreutils dependencies. This module will change `PATH` variable by prepending `/usr/local/opt/coreutils/libexec/gnubin` path. WDYT?

**Comment by fsquillace** [comment]
I am not a OSX expert, but I think in order to understand if the script is running on a OSX I could simply check that the path `/usr/local/opt/coreutils/libexec/gnubin` exists. Do you know an alternative way to do this?

**Comment by guhcampos** [comment]
I usually do a $(uname -s), this will return "Linux" on Linux boxes and "Darwin" for Mac OS X. I'm not sure for other flavors of BSD and POSIX though.

**Comment by fsquillace** [comment]
Change completed. Now, the user does not need to change the PATH variable anymore.
The installation process in OSX is greatly simplified: https://github.com/pearl-core/pearl#osx

However, Pearl packages that depends on GNU coreutils might be affected by this change although they will be easily fixed via the osx-compat.{fish,sh} files available: https://github.com/pearl-core/pearl/blob/master/lib/utils/osx-compat.sh

Thanks for catching this. It was a good one.
